export default {
  text: "white",
  border: "black",
  bgColor: "green",
  blue: "#4f6a7a",
  tomato: "#f9290c",
  gray: "gray",
  white: "white",
  red: "red",
  black: "black",
  headerColor: "#105089",
  skyblue: "skyblue",
  lightBlue: "#e1f1ff",
  semiSky: "#bcd9f1",
  nebiBlue: "#6f9bbf",
  darkGray: "#4a4a4a",
  lightGray: "#d3d3d3",
  green: "green",
  semiBlack: "#171815",
  lightRed: "#f9220ee0",
};
